name: Test coverage Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.4"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with coverage
      run: |
        coverage run --source="blobsapdi/db/","blobsapdi/entities" -m unittest discover tests/ && coverage report --fail-under=75
        coverage run --source="blobsapdi/objects","blobsapdi/exceptions" -m unittest discover tests && coverage report --fail-under=80
        coverage run --include="blobsapdi/services/*.py","blobsapdi/__init__.py" -m unittest discover tests && coverage report --fail-under=50
